tap "homebrew/bundle"

cask_args appdir: "~/Applications"

cask "google-chrome"
cask "alfred"

cask "font-meslo-lg-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-inconsolata-go-nerd-font"

brew "autojump"
brew "bat"
brew "fzf"
brew "kubernetes-cli"
brew "ranger"
brew "stow"
brew "thefuck"
brew "tree"
brew "pyenv"
brew "fasd"
